language: perl
perl:
  - "5.16"
  - "5.14"
  - "5.12"
env: PERL_MM_USE_DEFAULT=1
before_install:
  - cpan o conf init
  - cpanm CPAN::Uploader
install:
  - cpanm --quiet --notest --skip-satisfied Dist::Zilla
  - dzil authordeps | grep -vP '[^\w:]' | xargs -n 5 -P 10 cpanm --quiet --notest --skip-satisfied
  - export RELEASE_TESTING=1 AUTOMATED_TESTING=1 AUTHOR_TESTING=1 HARNESS_OPTIONS=j10:c HARNESS_TIMER=1
  - dzil listdeps | grep -vP '[^\w:]' |cpanm --verbose
script:
  - dzil smoke --release --author
notifications:
  email:
    - cartas@frederico.me
    - italo.goncales@gmail.com
